# Generated by Django 5.0.6 on 2024-07-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('specialization', models.CharField(choices=[('Admin', 'Administrator'), ('Doctor', 'Docteor')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='healthCareProffesions',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('proffession', models.CharField(choices=[('Radiologist', 'Radiologist'), ('clinicalMicrobiolodists', 'Clinicalmicrobiolodists'), ('clinicalBiochemist', 'Clinicalbiochemist')], max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('specialization', models.CharField(choices=[('Admin', 'Administrator'), ('Doctor', 'Docteor')], max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.admin')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.healthcareproffesions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_requested', models.DateField()),
                ('approval_status', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.admin')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('date_recorded', models.DateTimeField()),
                ('dateOf_birth', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(max_length=200)),
                ('medicalHistory', models.TextField(max_length=300)),
                ('testResult', models.TextField(max_length=200)),
                ('dateUpdate', models.DateField()),
                ('doctors', models.ManyToManyField(to='pages.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='patient',
            field=models.ManyToManyField(through='pages.Appointment', to='pages.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateRecorded', models.DateField()),
                ('testResult', models.TextField(max_length=200)),
                ('doctors', models.ManyToManyField(to='pages.doctor')),
                ('medicalRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.patient')),
            ],
        ),
    ]
