# Generated by Django 5.1.2 on 2024-10-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='phone', max_length=30, null=True),
        ),
    ]
