# Generated by Django 5.0.6 on 2024-07-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctortype',
            name='is_active',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctortype',
            name='code',
            field=models.CharField(choices=[('RAD', 'Rad'), ('MICRO', 'Micro'), ('BIOCHEM', 'Biochem'), ('GASTRO', 'Gastro')], max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctortype',
            name='department',
            field=models.CharField(choices=[('Radiology', 'Radiology'), ('Gastroenterology', 'Gastroenterology'), ('ClinicalLaboratoryDepartment', 'Clinicallaboratorydepartment')], max_length=200),
        ),
        migrations.AlterField(
            model_name='doctortype',
            name='proffession',
            field=models.CharField(choices=[('Radiologist', 'Radiologist'), ('ClinicalMicrobiologist', 'Clinicalmicrobiologist'), ('ClinicalBiochemist', 'Clinicalbiochemist'), ('ClinicalGastroenterology', 'Clinicalgastroenterology')], max_length=200),
        ),
    ]
