# Generated by Django 5.1.2 on 2024-10-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_customuser_code_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
