# Generated by Django 5.1.2 on 2024-10-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_customuser_code_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specialty',
        ),
    ]
