# Generated by Django 5.1.2 on 2024-11-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_customuser_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'administrator'), ('Doctor', 'doctor'), ('Patient', 'patient')], max_length=30),
        ),
    ]
